---
title: "flex1"
author: "Dwight Fonseka"
date: "April 28, 2017"
output: 
        flexdashboard::flex_dashboard:
        vertical_layout: scroll
runtime: "shiny"        
---

### Chart 1    
```{r, echo=FALSE}

selectInput(inputId = "n_breaks",
            label = "Number of bins in histogram (approximate):",
            choices = c(10, 20, 35, 50),
            selected = 20)

renderPlot({ 
         hist(faithful$eruptions,
         probability = TRUE,
         breaks = as.numeric(input$n_breaks),
         xlab = "Duration (minutes)",
         main = "Geyser eruption duration",
         width="500px",height="300px")
         })

```    

### Chart 2
```{r mtcars, echo=FALSE}

data(mtcars)
library(ggplot2)

fluidRow(
  column(3,
selectInput("x", "Choose an x var:",
                 choices = names(mtcars),
                 selected = "disp")
),
column(4,
selectInput("y", "Choose a y Var:",
                 choices = names(mtcars),
                 selected = "mpg")
))
    
renderPlot({
    x <- mtcars[, input$x]
    y <- mtcars[, input$y]
    plot(x,y, pch=16, col = "red",
    width="500px",height="300px")
  })

```